### ISSUE TITLE
Page crashes whenever clicking the SearchBar

### ISSUE THREAD

**Issue by rasgo-cc** [typesense/docusaurus-theme-search-typesense#32]
## Description

Clicking on the SearchBar crashes the page.

## Expected Behavior

The Search modal should open.

## Actual Behavior

![](https://imgur.com/w2UBH2b.png)

The full error on the console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'sendApiKeyAsQueryParam')
    at new SearchClient (SearchClient.js?414f:13:1)
    at eval (useSearchClient.js?34ab:15:1)
    at mountMemo (react-dom.development.js?ac89:15846:1)
    at Object.useMemo (react-dom.development.js?ac89:16219:1)
    at Object.useMemo (react.development.js?1b7e:1532:1)
    at useSearchClient (useSearchClient.js?34ab:14:1)
    at DocSearchModal (DocSearchModal.js?ee63:78:1)
    at renderWithHooks (react-dom.development.js?ac89:14985:1)
    at mountIndeterminateComponent (react-dom.development.js?ac89:17811:1)
    at beginWork (react-dom.development.js?ac89:19049:1)
react-dom.development.js?ac89:20085 The above error occurred in the <DocSearchModal> component:

    at DocSearchModal (webpack-internal:///./node_modules/typesense-docsearch-react/dist/esm/DocSearchModal.js:47:38)
    at DocSearch (webpack-internal:///./node_modules/docusaurus-theme-search-typesense/lib/theme/SearchBar/index.js:32:802)
    at SearchBar (webpack-internal:///./node_modules/docusaurus-theme-search-typesense/lib/theme/SearchBar/index.js:44:1896)
    at div
    at NavbarSearch (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Navbar/Search/index.js:13:36)
    at SearchNavbarItem (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/NavbarItem/SearchNavbarItem.js:13:40)
    at NavbarItem (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/NavbarItem/index.js:14:116)
    at NavbarItems (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Navbar/Content/index.js:23:128)
    at div
    at div
    at NavbarContentLayout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Navbar/Content/index.js:23:594)
    at NavbarContent (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Navbar/Content/index.js:23:1076)
    at nav
    at NavbarLayout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Navbar/Layout/index.js:19:413)
    at Navbar
    at NavbarSecondaryMenuDisplayProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/navbarSecondaryMenu/display.js:19:327)
    at NavbarMobileSidebarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/navbarMobileSidebar.js:21:423)
    at NavbarSecondaryMenuContentProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/navbarSecondaryMenu/content.js:14:156)
    at NavbarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/navbarUtils.js:20:38)
    at HtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:27:56)
    at PluginHtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:30:52)
    at DocsPreferredVersionContextProviderUnsafe (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:31:392)
    at DocsPreferredVersionContextProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:34:60)
    at ScrollControllerProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:18:488)
    at AnnouncementBarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/announcementBar.js:23:459)
    at ColorModeProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/colorMode.js:25:1255)
    at eval (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/reactUtils.js:65:19)
    at LayoutProvider (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/Provider/index.js:18:655)
    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/index.js:24:33)
    at DocPageLayout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocPage/Layout/index.js:17:37)
    at DocsSidebarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsSidebar.js:17:43)
    at DocsVersionProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsVersion.js:15:43)
    at HtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:27:56)
    at DocPage (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocPage/index.js:21:788)
    at RouteContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/routeContext.js:14:70)
    at LoadableComponent (webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:647:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:849:29)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:647:29)
    at ClientLifecyclesDispatcher (webpack-internal:///./node_modules/@docusaurus/core/lib/client/ClientLifecyclesDispatcher.js:15:271)
    at PendingNavigation (webpack-internal:///./node_modules/@docusaurus/core/lib/client/PendingNavigation.js:15:138)
    at Root (webpack-internal:///./node_modules/@docusaurus/core/lib/client/theme-fallback/Root/index.js:18:25)
    at BrowserContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/browserContext.js:19:126)
    at DocusaurusContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/docusaurusContext.js:19:495)
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:14:246)
    at App (webpack-internal:///./node_modules/@docusaurus/core/lib/client/App.js:26:241)
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:266:30)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:57:35)
    at r (webpack-internal:///./node_modules/react-helmet-async/lib/index.module.js:16:7320)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js?ac89:20085
useRouteContext.js?4ab8:6 Uncaught Error: Unexpected: no Docusaurus route context found
    at useRouteContext (useRouteContext.js?4ab8:6:1)
    at PluginHtmlClassNameProvider (metadataUtils.tsx?5c9e:102:1)
    at renderWithHooks (react-dom.development.js?ac89:14985:1)
    at mountIndeterminateComponent (react-dom.development.js?ac89:17811:1)
    at beginWork (react-dom.development.js?ac89:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at beginWork$1 (react-dom.development.js?ac89:23964:1)
    at performUnitOfWork (react-dom.development.js?ac89:22779:1)
react-dom.development.js?ac89:20085 The above error occurred in the <PluginHtmlClassNameProvider> component:

    at PluginHtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:30:52)
    at DocsPreferredVersionContextProviderUnsafe (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:31:392)
    at DocsPreferredVersionContextProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:34:60)
    at ScrollControllerProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:18:488)
    at AnnouncementBarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/announcementBar.js:23:459)
    at ColorModeProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/colorMode.js:25:1255)
    at eval (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/reactUtils.js:65:19)
    at LayoutProvider (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/Provider/index.js:18:655)
    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/index.js:24:33)
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:14:246)
    at Error (webpack-internal:///./node_modules/@docusaurus/core/lib/client/theme-fallback/Error/index.js:15:641)
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:14:246)
    at App (webpack-internal:///./node_modules/@docusaurus/core/lib/client/App.js:26:241)
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:266:30)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:57:35)
    at r (webpack-internal:///./node_modules/react-helmet-async/lib/index.module.js:16:7320)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

## Metadata

**Typesense Version**: 

```
"@docusaurus/core": "2.3.1",
"@docusaurus/preset-classic": "^2.3.1",
"docusaurus-theme-search-typesense": "^0.9.0",
```

**OS**:

**Comment by jasonbosco** [comment]
Could you confirm that you've added the `typesense` key to the docusaurus config like this: https://github.com/typesense/docusaurus-typesense-testground/blob/99d89aaaf740362b8928b0431374ea4903b3f7bc/docusaurus.config.js#L69-L94

If you have, could you fork that demo docusaurus project and try to replicate the issue?

**Comment by jasonbosco** [comment]
Feel free to re-open if this is still an issue
