### ISSUE TITLE
3.6.0 docusarus release breaks the search

### ISSUE THREAD

**Issue by Celtech** [typesense/docusaurus-theme-search-typesense#55]
## Description

If you compile a docusarus site on 3.6.0 you get the following error:

```
Hook useDocsPreferredVersionContext is called outside the <DocsPreferredVersionContextProvider>. 
ReactContextError
    at useDocsPreferredVersionContext (webpack-internal:///./node_modules/docusaurus-theme-search-typesense/node_modules/@docusaurus/plugin-content-docs/lib/client/docsPreferredVersion.js:35:329)
    at useDocsPreferredVersionByPluginId (webpack-internal:///./node_modules/docusaurus-theme-search-typesense/node_modules/@docusaurus/plugin-content-docs/lib/client/docsPreferredVersion.js:41:794)
    at Module.useDocsContextualSearchTags (webpack-internal:///./node_modules/docusaurus-theme-search-typesense/node_modules/@docusaurus/plugin-content-docs/lib/client/docsSearch.js:22:404)
    at useContextualSearchFilters (webpack-internal:///./node_modules/docusaurus-theme-search-typesense/node_modules/@docusaurus/theme-common/lib/index.js:91:167)
    at useTypesenseContextualFilters (webpack-internal:///./node_modules/docusaurus-theme-search-typesense/lib/client/useTypesenseContextualFacetFilters.js:12:145)
    at DocSearch (webpack-internal:///./node_modules/docusaurus-theme-search-typesense/lib/theme/SearchBar/index.js:33:1058)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15487:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20099:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21622:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14)
```

## Steps to reproduce

1. upgrade docusarus site with typesense search to 3.6.0
2. yarn start
3. see the error

## Metadata

**Typesense Version**: 0.22.0

**OS**: macOS

**Comment by jasonbosco** [comment]
@Celtech The fix for this is in `v0.23.0-0`. Could you give it a shot and let me know how it goes? 

CC: @tharropoulos

**Comment by rckennedy15** [comment]
@jasonbosco 

`v0.23.0-0` confirmed working with docusaurus `v3.7.0`!

**Comment by jasonbosco** [comment]
Published v0.23.0
